### ISSUE TITLE
Finalize 2.0.0

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_combinedvalues#14]
# TODO:
- [x] Bump PHP and Contao version (see MetaModels/core#1011)
- [x] Fix all remaining tickets tagged for 2.0.0
- [x] Check all file header (like https://github.com/MetaModels/core/blob/master/src/MetaModels/MetaModel.php#L1-L26)
- [x] Add `.check-author.yml` or check this
- [x] Add `.github/` templates - see [example](https://github.com/MetaModels/core/tree/e672fc555c7341059d76625cf0b5853b35c69070/.github) but ensure to update the links in the files!
- [x] Add `.gittattributes` file (see MetaModels/core#846)
- [x] remove `minimum-stability` from `composer.json` and add `"metamodels/core": "~2.0@alpha"` and `"contao-community-alliance/dc-general": "~2.0@beta"`
- [x] Ensure `LICENSE` file is present! (see https://github.com/MetaModels/core/blob/master/LICENSE)
- [x] Update badges in `README.md`! (look at first rows https://raw.githubusercontent.com/MetaModels/core/master/README.md)
- [x] Check build status is green!

**Comment by discordier** [comment]
All done in branch `hotfix/2.0.0-alpha2`

**Comment by zonky2** [comment]
Pls merge an tag this...

**Comment by discordier** [comment]
Did you test it?

**Comment by zonky2** [comment]
> Did you test it?

No! I don´t see any significant changes...

**Comment by discordier** [comment]
Ah? so what about a32fbf63bcb925f88da2f1ff25ddb6e30238df17 and f953bc59cbdec6c5da688ac4d8090a457fad1f77 then?

**Comment by zonky2** [comment]
and what about with https://github.com/MetaModels/attribute_combinedvalues/issues/7#issuecomment-222665616

**Comment by discordier** [comment]
Good point, hadn't this on my radar.

**Comment by zonky2** [comment]
no problem ... after 9 months ;-)

**Comment by discordier** [comment]
Done

**Comment by zonky2** [comment]
thx
